  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint(20) NOT NULL DEFAULT '0',
  `sms` text NOT NULL,
  `code` varchar(20) NOT NULL DEFAULT '',
  `res` text NOT NULL,
  `used` tinyint(4) NOT NULL DEFAULT '0',
  `dateline` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `user_id` (`user_id`),
  KEY `used` (`used`),
  KEY `dateline` (`dateline`)
