<section class="wil-section">
	<h2><span>Web Application Icons</span></h2>
	<div class="wil-font-icons-wrap">
		<div class="wil-icon"><a href="#"><i class="la la-adjust"></i> adjust </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-anchor"></i> anchor </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-archive"></i> archive </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-area-chart"></i> area-chart </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-arrows"></i> arrows </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-arrows-h"></i> arrows-h </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-arrows-v"></i> arrows-v </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-asterisk"></i> asterisk </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-at"></i> at </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-automobile"></i> automobile </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-balance-scale"></i> balance-scale </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-ban"></i> ban </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-bank"></i> bank </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-bar-chart"></i> bar-chart </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-bar-chart-o"></i> bar-chart-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-barcode"></i> barcode </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-bars"></i> bars </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-battery-0"></i> battery-0 </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-battery-1"></i> battery-1 </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-battery-2"></i> battery-2 </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-battery-3"></i> battery-3 </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-battery-4"></i> battery-4 </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-battery-empty"></i> battery-empty </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-battery-full"></i> battery-full </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-battery-half"></i> battery-half </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-battery-quarter"></i> battery-quarter </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-battery-three-quarters"></i> battery-three-quarters </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-bed"></i> bed </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-beer"></i> beer </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-bell"></i> bell </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-bell-o"></i> bell-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-bell-slash"></i> bell-slash </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-bell-slash-o"></i> bell-slash-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-bicycle"></i> bicycle </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-binoculars"></i> binoculars </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-birthday-cake"></i> birthday-cake </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-bolt"></i> bolt </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-bomb"></i> bomb </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-book"></i> book </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-bookmark"></i> bookmark </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-bookmark-o"></i> bookmark-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-briefcase"></i> briefcase </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-bug"></i> bug </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-building"></i> building </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-building-o"></i> building-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-bullhorn"></i> bullhorn </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-bullseye"></i> bullseye </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-bus"></i> bus </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-cab"></i> cab </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-calculator"></i> calculator </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-calendar"></i> calendar </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-calendar-check-o"></i> calendar-check-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-calendar-minus-o"></i> calendar-minus-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-calendar-o"></i> calendar-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-calendar-plus-o"></i> calendar-plus-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-calendar-times-o"></i> calendar-times-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-camera"></i> camera </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-camera-retro"></i> camera-retro </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-car"></i> car </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-caret-square-o-down"></i> caret-square-o-down </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-caret-square-o-left"></i> caret-square-o-left </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-caret-square-o-right"></i> caret-square-o-right </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-caret-square-o-up"></i> caret-square-o-up </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-cart-arrow-down"></i> cart-arrow-down </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-cart-plus"></i> cart-plus </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-cc"></i> cc </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-certificate"></i> certificate </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-check"></i> check </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-check-circle"></i> check-circle </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-check-circle-o"></i> check-circle-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-check-square"></i> check-square </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-check-square-o"></i> check-square-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-child"></i> child </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-circle"></i> circle </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-circle-o"></i> circle-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-circle-o-notch"></i> circle-o-notch </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-circle-thin"></i> circle-thin </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-clock-o"></i> clock-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-clone"></i> clone </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-close"></i> close </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-cloud"></i> cloud </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-cloud-download"></i> cloud-download </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-cloud-upload"></i> cloud-upload </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-code"></i> code </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-code-fork"></i> code-fork </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-coffee"></i> coffee </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-cog"></i> cog </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-cogs"></i> cogs </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-comment"></i> comment </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-comment-o"></i> comment-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-commenting"></i> commenting </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-commenting-o"></i> commenting-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-comments"></i> comments </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-comments-o"></i> comments-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-compass"></i> compass </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-copyright"></i> copyright </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-creative-commons"></i> creative-commons </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-credit-card"></i> credit-card </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-crop"></i> crop </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-crosshairs"></i> crosshairs </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-cube"></i> cube </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-cubes"></i> cubes </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-cutlery"></i> cutlery </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-dashboard"></i> dashboard </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-database"></i> database </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-desktop"></i> desktop </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-diamond"></i> diamond </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-dot-circle-o"></i> dot-circle-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-download"></i> download </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-edit"></i> edit </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-ellipsis-h"></i> ellipsis-h </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-ellipsis-v"></i> ellipsis-v </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-envelope"></i> envelope </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-envelope-o"></i> envelope-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-envelope-square"></i> envelope-square </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-eraser"></i> eraser </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-exchange"></i> exchange </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-exclamation"></i> exclamation </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-exclamation-circle"></i> exclamation-circle </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-exclamation-triangle"></i> exclamation-triangle </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-external-link"></i> external-link </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-external-link-square"></i> external-link-square </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-eye"></i> eye </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-eye-slash"></i> eye-slash </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-eyedropper"></i> eyedropper </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-fax"></i> fax </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-feed"></i> feed </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-female"></i> female </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-fighter-jet"></i> fighter-jet </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-file-archive-o"></i> file-archive-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-file-audio-o"></i> file-audio-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-file-code-o"></i> file-code-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-file-excel-o"></i> file-excel-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-file-image-o"></i> file-image-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-file-movie-o"></i> file-movie-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-file-pdf-o"></i> file-pdf-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-file-photo-o"></i> file-photo-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-file-picture-o"></i> file-picture-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-file-powerpoint-o"></i> file-powerpoint-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-file-sound-o"></i> file-sound-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-file-video-o"></i> file-video-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-file-word-o"></i> file-word-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-file-zip-o"></i> file-zip-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-film"></i> film </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-filter"></i> filter </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-fire"></i> fire </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-fire-extinguisher"></i> fire-extinguisher </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-flag"></i> flag </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-flag-checkered"></i> flag-checkered </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-flag-o"></i> flag-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-flash"></i> flash </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-flask"></i> flask </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-folder"></i> folder </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-folder-o"></i> folder-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-folder-open"></i> folder-open </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-folder-open-o"></i> folder-open-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-frown-o"></i> frown-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-futbol-o"></i> futbol-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-gamepad"></i> gamepad </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-gavel"></i> gavel </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-gear"></i> gear </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-gears"></i> gears </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-gift"></i> gift </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-glass"></i> glass </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-globe"></i> globe </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-graduation-cap"></i> graduation-cap </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-group"></i> group </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-hand-grab-o"></i> hand-grab-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-hand-lizard-o"></i> hand-lizard-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-hand-paper-o"></i> hand-paper-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-hand-peace-o"></i> hand-peace-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-hand-pointer-o"></i> hand-pointer-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-hand-rock-o"></i> hand-rock-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-hand-scissors-o"></i> hand-scissors-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-hand-spock-o"></i> hand-spock-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-hand-stop-o"></i> hand-stop-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-hdd-o"></i> hdd-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-headphones"></i> headphones </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-heart"></i> heart </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-heart-o"></i> heart-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-heartbeat"></i> heartbeat </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-history"></i> history </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-home"></i> home </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-hotel"></i> hotel </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-hourglass"></i> hourglass </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-hourglass-1"></i> hourglass-1 </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-hourglass-2"></i> hourglass-2 </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-hourglass-3"></i> hourglass-3 </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-hourglass-end"></i> hourglass-end </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-hourglass-half"></i> hourglass-half </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-hourglass-o"></i> hourglass-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-hourglass-start"></i> hourglass-start </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-i-cursor"></i> i-cursor </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-image"></i> image </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-inbox"></i> inbox </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-industry"></i> industry </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-info"></i> info </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-info-circle"></i> info-circle </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-institution"></i> institution </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-key"></i> key </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-keyboard-o"></i> keyboard-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-language"></i> language </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-laptop"></i> laptop </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-leaf"></i> leaf </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-legal"></i> legal </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-lemon-o"></i> lemon-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-level-down"></i> level-down </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-level-up"></i> level-up </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-life-bouy"></i> life-bouy </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-life-buoy"></i> life-buoy </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-life-ring"></i> life-ring </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-life-saver"></i> life-saver </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-lightbulb-o"></i> lightbulb-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-line-chart"></i> line-chart </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-location-arrow"></i> location-arrow </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-lock"></i> lock </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-magic"></i> magic </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-magnet"></i> magnet </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-mail-forward"></i> mail-forward </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-mail-reply"></i> mail-reply </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-mail-reply-all"></i> mail-reply-all </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-male"></i> male </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-map"></i> map </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-map-marker"></i> map-marker </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-map-o"></i> map-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-map-pin"></i> map-pin </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-map-signs"></i> map-signs </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-meh-o"></i> meh-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-microphone"></i> microphone </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-microphone-slash"></i> microphone-slash </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-minus"></i> minus </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-minus-circle"></i> minus-circle </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-minus-square"></i> minus-square </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-minus-square-o"></i> minus-square-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-mobile"></i> mobile </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-mobile-phone"></i> mobile-phone </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-money"></i> money </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-moon-o"></i> moon-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-mortar-board"></i> mortar-board </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-motorcycle"></i> motorcycle </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-mouse-pointer"></i> mouse-pointer </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-music"></i> music </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-navicon"></i> navicon </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-newspaper-o"></i> newspaper-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-object-group"></i> object-group </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-object-ungroup"></i> object-ungroup </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-paint-brush"></i> paint-brush </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-paper-plane"></i> paper-plane </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-paper-plane-o"></i> paper-plane-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-paw"></i> paw </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-pencil"></i> pencil </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-pencil-square"></i> pencil-square </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-pencil-square-o"></i> pencil-square-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-phone"></i> phone </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-phone-square"></i> phone-square </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-photo"></i> photo </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-picture-o"></i> picture-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-pie-chart"></i> pie-chart </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-plane"></i> plane </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-plug"></i> plug </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-plus"></i> plus </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-plus-circle"></i> plus-circle </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-plus-square"></i> plus-square </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-plus-square-o"></i> plus-square-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-power-off"></i> power-off </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-print"></i> print </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-puzzle-piece"></i> puzzle-piece </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-qrcode"></i> qrcode </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-question"></i> question </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-question-circle"></i> question-circle </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-quote-left"></i> quote-left </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-quote-right"></i> quote-right </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-random"></i> random </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-recycle"></i> recycle </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-refresh"></i> refresh </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-registered"></i> registered </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-remove"></i> remove </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-reorder"></i> reorder </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-reply"></i> reply </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-reply-all"></i> reply-all </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-retweet"></i> retweet </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-road"></i> road </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-rocket"></i> rocket </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-rss"></i> rss </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-rss-square"></i> rss-square </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-search"></i> search </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-search-minus"></i> search-minus </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-search-plus"></i> search-plus </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-send"></i> send </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-send-o"></i> send-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-server"></i> server </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-share"></i> share </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-share-alt"></i> share-alt </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-share-alt-square"></i> share-alt-square </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-share-square"></i> share-square </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-share-square-o"></i> share-square-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-shield"></i> shield </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-ship"></i> ship </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-shopping-cart"></i> shopping-cart </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-sign-in"></i> sign-in </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-sign-out"></i> sign-out </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-signal"></i> signal </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-sitemap"></i> sitemap </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-sliders"></i> sliders </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-smile-o"></i> smile-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-soccer-ball-o"></i> soccer-ball-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-sort"></i> sort </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-sort-alpha-asc"></i> sort-alpha-asc </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-sort-alpha-desc"></i> sort-alpha-desc </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-sort-amount-asc"></i> sort-amount-asc </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-sort-amount-desc"></i> sort-amount-desc </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-sort-asc"></i> sort-asc </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-sort-desc"></i> sort-desc </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-sort-down"></i> sort-down </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-sort-numeric-asc"></i> sort-numeric-asc </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-sort-numeric-desc"></i> sort-numeric-desc </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-sort-up"></i> sort-up </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-space-shuttle"></i> space-shuttle </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-spinner"></i> spinner </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-spoon"></i> spoon </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-square"></i> square </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-square-o"></i> square-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-star"></i> star </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-star-half"></i> star-half </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-star-half-empty"></i> star-half-empty </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-star-half-full"></i> star-half-full </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-star-half-o"></i> star-half-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-star-o"></i> star-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-sticky-note"></i> sticky-note </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-sticky-note-o"></i> sticky-note-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-street-view"></i> street-view </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-suitcase"></i> suitcase </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-sun-o"></i> sun-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-support"></i> support </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-tablet"></i> tablet </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-tachometer"></i> tachometer </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-tag"></i> tag </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-tags"></i> tags </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-tasks"></i> tasks </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-taxi"></i> taxi </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-television"></i> television </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-terminal"></i> terminal </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-thumb-tack"></i> thumb-tack </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-thumbs-down"></i> thumbs-down </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-thumbs-o-down"></i> thumbs-o-down </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-thumbs-o-up"></i> thumbs-o-up </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-thumbs-up"></i> thumbs-up </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-ticket"></i> ticket </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-times"></i> times </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-times-circle"></i> times-circle </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-times-circle-o"></i> times-circle-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-tint"></i> tint </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-toggle-down"></i> toggle-down </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-toggle-left"></i> toggle-left </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-toggle-off"></i> toggle-off </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-toggle-on"></i> toggle-on </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-toggle-right"></i> toggle-right </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-toggle-up"></i> toggle-up </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-trademark"></i> trademark </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-trash"></i> trash </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-trash-o"></i> trash-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-tree"></i> tree </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-trophy"></i> trophy </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-truck"></i> truck </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-tty"></i> tty </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-tv"></i> tv </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-umbrella"></i> umbrella </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-university"></i> university </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-unlock"></i> unlock </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-unlock-alt"></i> unlock-alt </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-unsorted"></i> unsorted </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-upload"></i> upload </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-user"></i> user </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-user-plus"></i> user-plus </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-user-secret"></i> user-secret </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-user-times"></i> user-times </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-users"></i> users </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-video-camera"></i> video-camera </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-volume-down"></i> volume-down </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-volume-off"></i> volume-off </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-volume-up"></i> volume-up </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-warning"></i> warning </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-wheelchair"></i> wheelchair </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-wifi"></i> wifi </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-wrench"></i> wrench </a></div>
	</div>
</section>
<section class="wil-section">
	<h2><span>Hand Icons</span></h2>
	<div class="wil-font-icons-wrap">
		<div class="wil-icon"><a href="#"><i class="la la-hand-grab-o"></i> hand-grab-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-hand-lizard-o"></i> hand-lizard-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-hand-paper-o"></i> hand-paper-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-hand-peace-o"></i> hand-peace-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-hand-pointer-o"></i> hand-pointer-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-hand-rock-o"></i> hand-rock-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-hand-scissors-o"></i> hand-scissors-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-hand-spock-o"></i> hand-spock-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-hand-stop-o"></i> hand-stop-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-thumbs-down"></i> thumbs-down </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-thumbs-o-down"></i> thumbs-o-down </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-thumbs-o-up"></i> thumbs-o-up </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-thumbs-up"></i> thumbs-up </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-hand-o-down"></i> hand-o-down </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-hand-o-left"></i> hand-o-left </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-hand-o-right"></i> hand-o-right </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-hand-o-up"></i> hand-o-up </a></div>
	</div>
</section>
<section class="wil-section">
	<h2><span>Transportation Icons</span></h2>
	<div class="wil-font-icons-wrap">
		<div class="wil-icon"><a href="#"><i class="la la-automobile"></i> automobile </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-bicycle"></i> bicycle </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-bus"></i> bus </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-cab"></i> cab </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-car"></i> car </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-fighter-jet"></i> fighter-jet </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-motorcycle"></i> motorcycle </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-plane"></i> plane </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-rocket"></i> rocket </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-ship"></i> ship </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-space-shuttle"></i> space-shuttle </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-taxi"></i> taxi </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-truck"></i> truck </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-wheelchair"></i> wheelchair </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-ambulance"></i> ambulance </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-subway"></i> subway </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-train"></i> train </a></div>
	</div>
</section>
<section class="wil-section">
	<h2><span>Gender Icons</span></h2>
	<div class="wil-font-icons-wrap">
		<div class="wil-icon"><a href="#"><i class="la la-genderless"></i> genderless </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-intersex"></i> intersex </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-mars"></i> mars </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-mars-double"></i> mars-double </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-mars-stroke"></i> mars-stroke </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-mars-stroke-h"></i> mars-stroke-h </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-mars-stroke-v"></i> mars-stroke-v </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-mercury"></i> mercury </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-neuter"></i> neuter </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-transgender"></i> transgender </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-transgender-alt"></i> transgender-alt </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-venus"></i> venus </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-venus-double"></i> venus-double </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-venus-mars"></i> venus-mars </a></div>
	</div>
</section>
<section class="wil-section">
	<h2><span>File Type Icons</span></h2>
	<div class="wil-font-icons-wrap">
		<div class="wil-icon"><a href="#"><i class="la la-file-archive-o"></i> file-archive-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-file-audio-o"></i> file-audio-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-file-code-o"></i> file-code-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-file-excel-o"></i> file-excel-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-file-image-o"></i> file-image-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-file-movie-o"></i> file-movie-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-file-pdf-o"></i> file-pdf-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-file-photo-o"></i> file-photo-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-file-picture-o"></i> file-picture-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-file-powerpoint-o"></i> file-powerpoint-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-file-sound-o"></i> file-sound-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-file-video-o"></i> file-video-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-file-word-o"></i> file-word-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-file-zip-o"></i> file-zip-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-file"></i> file </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-file-o"></i> file-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-file-text"></i> file-text </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-file-text-o"></i> file-text-o </a></div>
	</div>
</section>
<section class="wil-section">
	<h2><span>Spinner Icons</span></h2>
	<div class="wil-font-icons-wrap">
		<div class="wil-icon"><a href="#"><i class="la la-circle-o-notch"></i> circle-o-notch </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-cog"></i> cog </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-gear"></i> gear </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-refresh"></i> refresh </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-spinner"></i> spinner </a></div>
	</div>
</section>
<section class="wil-section">
	<h2><span>Form Control Icons</span></h2>
	<div class="wil-font-icons-wrap">
		<div class="wil-icon"><a href="#"><i class="la la-check-square"></i> check-square </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-check-square-o"></i> check-square-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-circle"></i> circle </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-circle-o"></i> circle-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-dot-circle-o"></i> dot-circle-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-minus-square"></i> minus-square </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-minus-square-o"></i> minus-square-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-plus-square"></i> plus-square </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-plus-square-o"></i> plus-square-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-square"></i> square </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-square-o"></i> square-o </a></div>
	</div>
</section>
<section class="wil-section">
	<h2><span>Payment Icons</span></h2>
	<div class="wil-font-icons-wrap">
		<div class="wil-icon"><a href="#"><i class="la la-credit-card"></i> credit-card </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-cc-amex"></i> cc-amex </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-cc-diners-club"></i> cc-diners-club </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-cc-discover"></i> cc-discover </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-cc-jcb"></i> cc-jcb </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-cc-mastercard"></i> cc-mastercard </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-cc-paypal"></i> cc-paypal </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-cc-stripe"></i> cc-stripe </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-cc-visa"></i> cc-visa </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-google-wallet"></i> google-wallet </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-paypal"></i> paypal </a></div>
	</div>
</section>
<section class="wil-section">
	<h2><span>Chart Icons</span></h2>
	<div class="wil-font-icons-wrap">
		<div class="wil-icon"><a href="#"><i class="la la-area-chart"></i> area-chart </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-bar-chart"></i> bar-chart </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-bar-chart-o"></i> bar-chart-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-line-chart"></i> line-chart </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-pie-chart"></i> pie-chart </a></div>
	</div>
</section>
<section class="wil-section">
	<h2><span>Currency Icons</span></h2>
	<div class="wil-font-icons-wrap">
		<div class="wil-icon"><a href="#"><i class="la la-money"></i> money </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-bitcoin"></i> bitcoin </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-btc"></i> btc </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-cny"></i> cny </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-dollar"></i> dollar </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-eur"></i> eur </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-euro"></i> euro </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-gbp"></i> gbp </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-gg"></i> gg </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-gg-circle"></i> gg-circle </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-ils"></i> ils </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-inr"></i> inr </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-jpy"></i> jpy </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-krw"></i> krw </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-rmb"></i> rmb </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-rouble"></i> rouble </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-rub"></i> rub </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-ruble"></i> ruble </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-rupee"></i> rupee </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-shekel"></i> shekel </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-sheqel"></i> sheqel </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-try"></i> try </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-turkish-lira"></i> turkish-lira </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-usd"></i> usd </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-won"></i> won </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-yen"></i> yen </a></div>
	</div>
</section>
<section class="wil-section">
	<h2><span>Text Editor Icons</span></h2>
	<div class="wil-font-icons-wrap">
		<div class="wil-icon"><a href="#"><i class="la la-eraser"></i> eraser </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-file"></i> file </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-file-o"></i> file-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-file-text"></i> file-text </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-file-text-o"></i> file-text-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-align-center"></i> align-center </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-align-justify"></i> align-justify </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-align-left"></i> align-left </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-align-right"></i> align-right </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-bold"></i> bold </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-chain"></i> chain </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-chain-broken"></i> chain-broken </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-clipboard"></i> clipboard </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-columns"></i> columns </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-copy"></i> copy </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-cut"></i> cut </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-dedent"></i> dedent </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-files-o"></i> files-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-floppy-o"></i> floppy-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-font"></i> font </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-header"></i> header </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-indent"></i> indent </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-italic"></i> italic </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-link"></i> link </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-list"></i> list </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-list-alt"></i> list-alt </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-list-ol"></i> list-ol </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-list-ul"></i> list-ul </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-outdent"></i> outdent </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-paperclip"></i> paperclip </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-paragraph"></i> paragraph </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-paste"></i> paste </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-repeat"></i> repeat </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-rotate-left"></i> rotate-left </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-rotate-right"></i> rotate-right </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-save"></i> save </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-scissors"></i> scissors </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-strikethrough"></i> strikethrough </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-subscript"></i> subscript </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-superscript"></i> superscript </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-table"></i> table </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-text-height"></i> text-height </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-text-width"></i> text-width </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-th"></i> th </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-th-large"></i> th-large </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-th-list"></i> th-list </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-underline"></i> underline </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-undo"></i> undo </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-unlink"></i> unlink </a></div>
	</div>
</section>
<section class="wil-section">
	<h2><span>Directional Icons</span></h2>
	<div class="wil-font-icons-wrap">
		<div class="wil-icon"><a href="#"><i class="la la-arrows"></i> arrows </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-arrows-h"></i> arrows-h </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-arrows-v"></i> arrows-v </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-caret-square-o-down"></i> caret-square-o-down </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-caret-square-o-left"></i> caret-square-o-left </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-caret-square-o-right"></i> caret-square-o-right </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-caret-square-o-up"></i> caret-square-o-up </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-exchange"></i> exchange </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-toggle-down"></i> toggle-down </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-toggle-left"></i> toggle-left </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-toggle-right"></i> toggle-right </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-toggle-up"></i> toggle-up </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-hand-o-down"></i> hand-o-down </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-hand-o-left"></i> hand-o-left </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-hand-o-right"></i> hand-o-right </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-hand-o-up"></i> hand-o-up </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-angle-double-down"></i> angle-double-down </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-angle-double-left"></i> angle-double-left </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-angle-double-right"></i> angle-double-right </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-angle-double-up"></i> angle-double-up </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-angle-down"></i> angle-down </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-angle-left"></i> angle-left </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-angle-right"></i> angle-right </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-angle-up"></i> angle-up </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-arrow-circle-down"></i> arrow-circle-down </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-arrow-circle-left"></i> arrow-circle-left </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-arrow-circle-o-down"></i> arrow-circle-o-down </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-arrow-circle-o-left"></i> arrow-circle-o-left </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-arrow-circle-o-right"></i> arrow-circle-o-right </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-arrow-circle-o-up"></i> arrow-circle-o-up </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-arrow-circle-right"></i> arrow-circle-right </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-arrow-circle-up"></i> arrow-circle-up </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-arrow-down"></i> arrow-down </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-arrow-left"></i> arrow-left </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-arrow-right"></i> arrow-right </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-arrow-up"></i> arrow-up </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-arrows-alt"></i> arrows-alt </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-caret-down"></i> caret-down </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-caret-left"></i> caret-left </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-caret-right"></i> caret-right </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-caret-up"></i> caret-up </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-chevron-circle-down"></i></i> chevron-circle-down </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-chevron-circle-left"></i></i> chevron-circle-left </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-chevron-circle-right"></i> chevron-circle-right </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-chevron-circle-up"></i> chevron-circle-up </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-chevron-down"></i> chevron-down </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-chevron-left"></i> chevron-left </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-chevron-right"></i> chevron-right </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-chevron-up"></i> chevron-up </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-long-arrow-down"></i> long-arrow-down </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-long-arrow-left"></i> long-arrow-left </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-long-arrow-right"></i> long-arrow-right </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-long-arrow-up"></i> long-arrow-up </a></div>
	</div>
</section>
<section class="wil-section">
	<h2><span>Video Player Icons</span></h2>
	<div class="wil-font-icons-wrap">
		<div class="wil-icon"><a href="#"><i class="la la-random"></i> random </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-arrows-alt"></i> arrows-alt </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-backward"></i> backward </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-compress"></i> compress </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-eject"></i> eject </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-expand"></i> expand </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-fast-backward"></i> fast-backward </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-fast-forward"></i> fast-forward </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-forward"></i> forward </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-pause"></i> pause </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-play"></i> play </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-play-circle"></i> play-circle </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-play-circle-o"></i> play-circle-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-step-backward"></i> step-backward </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-step-forward"></i> step-forward </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-stop"></i> stop </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-youtube-play"></i> youtube-play </a></div>
	</div>
</section>
<section class="wil-section">
	<h2><span>Brand Icons</span></h2>
	<div class="wil-font-icons-wrap">
		<div class="wil-icon"><a href="#"><i class="la la-share-alt"></i> share-alt </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-share-alt-square"></i> share-alt-square </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-cc-amex"></i> cc-amex </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-cc-diners-club"></i> cc-diners-club </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-cc-discover"></i> cc-discover </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-cc-jcb"></i> cc-jcb </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-cc-mastercard"></i> cc-mastercard </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-cc-paypal"></i> cc-paypal </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-cc-stripe"></i> cc-stripe </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-cc-visa"></i> cc-visa </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-google-wallet"></i> google-wallet </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-paypal"></i> paypal </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-bitcoin"></i> bitcoin </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-btc"></i> btc </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-gg"></i> gg </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-gg-circle"></i> gg-circle </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-youtube-play"></i> youtube-play </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-500px"></i> 500px </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-adn"></i> adn </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-amazon"></i> amazon </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-android"></i> android </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-angellist"></i> angellist </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-apple"></i> apple </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-behance"></i> behance </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-behance-square"></i> behance-square </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-bitbucket"></i> bitbucket </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-bitbucket-square"></i> bitbucket-square </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-black-tie"></i> black-tie </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-buysellads"></i> buysellads </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-chrome"></i> chrome </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-codepen"></i> codepen </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-connectdevelop"></i> connectdevelop </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-contao"></i> contao </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-css3"></i> css3 </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-dashcube"></i> dashcube </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-delicious"></i> delicious </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-deviantart"></i> deviantart </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-digg"></i> digg </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-dribbble"></i> dribbble </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-dropbox"></i> dropbox </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-drupal"></i> drupal </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-empire"></i> empire </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-expeditedssl"></i> expeditedssl </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-facebook"></i> facebook </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-facebook-f"></i> facebook-f </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-facebook-official"></i> facebook-official </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-facebook-square"></i> facebook-square </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-firefox"></i> firefox </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-flickr"></i> flickr </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-fonticons"></i> fonticons </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-forumbee"></i> forumbee </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-foursquare"></i> foursquare </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-ge"></i> ge </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-get-pocket"></i> get-pocket </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-git"></i> git </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-git-square"></i> git-square </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-github"></i> github </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-github-alt"></i> github-alt </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-github-square"></i> github-square </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-gittip"></i> gittip </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-google"></i> google </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-google-plus"></i> google-plus </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-google-plus-square"></i> google-plus-square </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-gratipay"></i> gratipay </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-hacker-news"></i> hacker-news </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-houzz"></i> houzz </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-html5"></i> html5 </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-instagram"></i> instagram </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-internet-explorer"></i> internet-explorer </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-ioxhost"></i> ioxhost </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-joomla"></i> joomla </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-jsfiddle"></i> jsfiddle </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-lastfm"></i> lastfm </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-lastfm-square"></i> lastfm-square </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-leanpub"></i> leanpub </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-linkedin"></i> linkedin </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-linkedin-square"></i> linkedin-square </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-linux"></i> linux </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-maxcdn"></i> maxcdn </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-meanpath"></i> meanpath </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-medium"></i> medium </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-odnoklassniki"></i> odnoklassniki </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-odnoklassniki-square"></i> odnoklassniki-square </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-opencart"></i> opencart </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-openid"></i> openid </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-opera"></i> opera </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-optin-monster"></i> optin-monster </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-pagelines"></i> pagelines </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-pied-piper"></i> pied-piper </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-pied-piper-alt"></i> pied-piper-alt </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-pinterest"></i> pinterest </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-pinterest-p"></i> pinterest-p </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-pinterest-square"></i> pinterest-square </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-qq"></i> qq </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-ra"></i> ra </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-rebel"></i> rebel </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-reddit"></i> reddit </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-reddit-square"></i> reddit-square </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-renren"></i> renren </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-safari"></i> safari </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-sellsy"></i> sellsy </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-shirtsinbulk"></i> shirtsinbulk </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-simplybuilt"></i> simplybuilt </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-skyatlas"></i> skyatlas </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-skype"></i> skype </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-slack"></i> slack </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-slideshare"></i> slideshare </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-soundcloud"></i> soundcloud </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-spotify"></i> spotify </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-stack-exchange"></i> stack-exchange </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-stack-overflow"></i> stack-overflow </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-steam"></i> steam </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-steam-square"></i> steam-square </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-stumbleupon"></i> stumbleupon </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-stumbleupon-circle"></i> stumbleupon-circle </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-tencent-weibo"></i> tencent-weibo </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-trello"></i> trello </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-tripadvisor"></i> tripadvisor </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-tumblr"></i> tumblr </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-tumblr-square"></i> tumblr-square </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-twitch"></i> twitch </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-twitter"></i> twitter </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-twitter-square"></i> twitter-square </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-viacoin"></i> viacoin </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-vimeo"></i> vimeo </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-vimeo-square"></i> vimeo-square </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-vine"></i> vine </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-vk"></i> vk </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-wechat"></i> wechat </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-weibo"></i> weibo </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-weixin"></i> weixin </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-whatsapp"></i> whatsapp </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-wikipedia-w"></i> wikipedia-w </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-windows"></i> windows </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-wordpress"></i> wordpress </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-xing"></i> xing </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-xing-square"></i> xing-square </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-y-combinator"></i> y-combinator </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-y-combinator-square"></i> y-combinator-square </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-yahoo"></i> yahoo </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-yc"></i> yc </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-yc-square"></i> yc-square </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-yelp"></i> yelp </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-youtube"></i> youtube </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-youtube-square"></i> youtube-square </a></div>
	</div>
</section>
<section class="wil-section">
	<h2><span>Medical Icons</span></h2>
	<div class="wil-font-icons-wrap">
		<div class="wil-icon"><a href="#"><i class="la la-heart"></i> heart </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-heart-o"></i> heart-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-heartbeat"></i> heartbeat </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-plus-square"></i> plus-square </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-wheelchair"></i> wheelchair </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-ambulance"></i> ambulance </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-h-square"></i> h-square </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-hospital-o"></i> hospital-o </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-medkit"></i> medkit </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-stethoscope"></i> stethoscope </a></div>
		<div class="wil-icon"><a href="#"><i class="la la-user-md"></i> user-md </a></div>
	</div>
</section>