<?php
return apply_filters(
	'wiloke-listing-tools/config/middleware',
	[
		'addListingValidation'          => 'WilokeListingTools\Middleware\AddListingValidation',
		'isPassedPostAuthor'            => 'WilokeListingTools\Middleware\IsPassedPostAuthor',
		'isGatewaySupported'            => 'WilokeListingTools\Middleware\IsGatewaySupported',
		'isPlanExists'                  => 'WilokeListingTools\Middleware\IsPlanExists',
		'validateBeforeSetUserPlan'     => 'WilokeListingTools\Middleware\ValidationBeforeSetUserPlan',
		'isUserLoggedIn'                => 'WilokeListingTools\Middleware\IsUserLoggedIn',
		'verifyDirectBankTransfer'      => 'WilokeListingTools\Middleware\VerifyDirectBankTransfer',
		'isAdministrator'               => 'WilokeListingTools\Middleware\IsAdministrator',
		'designListingRoles'            => 'WilokeListingTools\Middleware\DesignListingRoles',
		'isListingPostType'             => 'WilokeListingTools\Middleware\IsListingPostType',
		'verifyReview'                  => 'WilokeListingTools\Middleware\VerifyReview',
		'isReviewExists'                => 'WilokeListingTools\Middleware\IsReviewExists',
		'isPublishingListing'           => 'WilokeListingTools\Middleware\IsPublishingListing',
		'isOwnerOfPost'                 => 'WilokeListingTools\Middleware\IsOwnerOfPost',
		'addressRequired'               => 'WilokeListingTools\Middleware\AddressRequired',
		'isPostAuthor'                  => 'WilokeListingTools\Middleware\IsPostAuthor',
		'isClaimAvailable'              => 'WilokeListingTools\Middleware\IsClaimAvailable',
		'isPublishedPost'               => 'WilokeListingTools\Middleware\IsPublishedPost',
		'isPostType'                    => 'WilokeListingTools\Middleware\IsPostType',
		'isReviewEnabled'               => 'WilokeListingTools\Middleware\IsReviewEnabled',
		'isAllowEditingPublishedListing'=> 'WilokeListingTools\Middleware\IsAllowEditingPublishedListing',
		'isListingBeingReviewed'        => 'WilokeListingTools\Middleware\IsListingBeingReviewed',
		'isSupportedPostTypeAddListing' => 'WilokeListingTools\Middleware\IsSupportedPostTypeAddListing',
		'beforeSubmitMessage'           => 'WilokeListingTools\Middleware\BeforeSubmitMessage',
		'isWilokeShortcodeActivated'    => 'WilokeListingTools\Middleware\IsWilokeShortcodeActivated',
		'isThemeOptionSupport'          => 'WilokeListingTools\Middleware\IsThemeOptionSupport',
		'canSubmissionListing'          => 'WilokeListingTools\Middleware\CanSubmissionListing',
		'isExceededFreePlan'            => 'WilokeListingTools\Middleware\IsExceededFreePlan',
		'isTemporaryHiddenPost'         => 'WilokeListingTools\Middleware\IsTemporaryHiddenPost',
		'isCurrentPlanAvailable'        => 'WilokeListingTools\Middleware\IsCurrentPlanAvailable',
		'isMyPaymentSession'            => 'WilokeListingTools\Middleware\IsMyPaymentSession',
		'isExceededMaximumListing'      => 'WilokeListingTools\Middleware\IsExceededMaximumListingInRecurringPlan',
		'isAccountConfirmed'            => 'WilokeListingTools\Middleware\IsAccountConfirmed',
		'iAgreeToPrivacyPolicy'            => 'WilokeListingTools\Middleware\IAgreeToPrivacyPolicy',
		'iAgreeToTerms'            => 'WilokeListingTools\Middleware\IAgreeToTerms',
		'canRegister'            => 'WilokeListingTools\Middleware\CanRegister',
		'validateGoogleReCaptcha'            => 'WilokeListingTools\Middleware\ValidateGoogleReCaptcha'
	]
);